package h

import (
	gh "maragu.dev/gomponents/html"
)

func A(children ...H) H          { return gh.A(children...) }
func Abbr(children ...H) H       { return gh.Abbr(children...) }
func Address(children ...H) H    { return gh.Address(children...) }
func Area(children ...H) H       { return gh.Area(children...) }
func Article(children ...H) H    { return gh.Article(children...) }
func Aside(children ...H) H      { return gh.Aside(children...) }
func Audio(children ...H) H      { return gh.Audio(children...) }
func B(children ...H) H          { return gh.B(children...) }
func Base(children ...H) H       { return gh.Base(children...) }
func BlockQuote(children ...H) H { return gh.BlockQuote(children...) }
func Body(children ...H) H       { return gh.Body(children...) }
func Br(children ...H) H         { return gh.Br(children...) }
func Button(children ...H) H     { return gh.Button(children...) }
func Canvas(children ...H) H     { return gh.Canvas(children...) }
func Caption(children ...H) H    { return gh.Caption(children...) }
func Cite(children ...H) H       { return gh.Cite(children...) }
func Code(children ...H) H       { return gh.Code(children...) }
func Col(children ...H) H        { return gh.Col(children...) }
func ColGroup(children ...H) H   { return gh.ColGroup(children...) }
func DataList(children ...H) H   { return gh.DataList(children...) }
func Dd(children ...H) H         { return gh.Dd(children...) }
func Del(children ...H) H        { return gh.Del(children...) }
func Details(children ...H) H    { return gh.Details(children...) }
func Dfn(children ...H) H        { return gh.Dfn(children...) }
func Dialog(children ...H) H     { return gh.Dialog(children...) }
func Div(children ...H) H        { return gh.Div(children...) }
func Dl(children ...H) H         { return gh.Dl(children...) }
func Dt(children ...H) H         { return gh.Dt(children...) }
func Em(children ...H) H         { return gh.Em(children...) }
func Embed(children ...H) H      { return gh.Embed(children...) }
func FieldSet(children ...H) H   { return gh.FieldSet(children...) }
func FigCaption(children ...H) H { return gh.FigCaption(children...) }
func Figure(children ...H) H     { return gh.Figure(children...) }
func Footer(children ...H) H     { return gh.Footer(children...) }
func Form(children ...H) H       { return gh.Form(children...) }
func H1(children ...H) H         { return gh.H1(children...) }
func H2(children ...H) H         { return gh.H2(children...) }
func H3(children ...H) H         { return gh.H3(children...) }
func H4(children ...H) H         { return gh.H4(children...) }
func H5(children ...H) H         { return gh.H5(children...) }
func H6(children ...H) H         { return gh.H6(children...) }
func Head(children ...H) H       { return gh.Head(children...) }
func Header(children ...H) H     { return gh.Header(children...) }
func Hr(children ...H) H         { return gh.Hr(children...) }
func HGroup(children ...H) H     { return gh.HGroup(children...) }
func HTML(children ...H) H       { return gh.HTML(children...) }
func I(children ...H) H          { return gh.I(children...) }
func IFrame(children ...H) H     { return gh.IFrame(children...) }
func Img(children ...H) H        { return gh.Img(children...) }
func Input(children ...H) H      { return gh.Input(children...) }
func Ins(children ...H) H        { return gh.Ins(children...) }
func Kbd(children ...H) H        { return gh.Kbd(children...) }
func Label(children ...H) H      { return gh.Label(children...) }
func Legend(children ...H) H     { return gh.Legend(children...) }
func Li(children ...H) H         { return gh.Li(children...) }
func Link(children ...H) H       { return gh.Link(children...) }
func Main(children ...H) H       { return gh.Main(children...) }
func Mark(children ...H) H       { return gh.Mark(children...) }
func Meta(children ...H) H       { return gh.Meta(children...) }
func Meter(children ...H) H      { return gh.Meter(children...) }
func Nav(children ...H) H        { return gh.Nav(children...) }
func NoScript(children ...H) H   { return gh.NoScript(children...) }
func Object(children ...H) H     { return gh.Object(children...) }
func Ol(children ...H) H         { return gh.Ol(children...) }
func OptGroup(children ...H) H   { return gh.OptGroup(children...) }
func Option(children ...H) H     { return gh.Option(children...) }
func P(children ...H) H          { return gh.P(children...) }
func Picture(children ...H) H    { return gh.Picture(children...) }
func Pre(children ...H) H        { return gh.Pre(children...) }
func Progress(children ...H) H   { return gh.Progress(children...) }
func Q(children ...H) H          { return gh.Q(children...) }
func S(children ...H) H          { return gh.S(children...) }
func Samp(children ...H) H       { return gh.Samp(children...) }
func Script(children ...H) H     { return gh.Script(children...) }
func Section(children ...H) H    { return gh.Section(children...) }
func Select(children ...H) H     { return gh.Select(children...) }
func Small(children ...H) H      { return gh.Small(children...) }
func Source(children ...H) H     { return gh.Source(children...) }
func Span(children ...H) H       { return gh.Span(children...) }
func Strong(children ...H) H     { return gh.Strong(children...) }
func Style(v string) H           { return gh.Style(v) }
func Sub(children ...H) H        { return gh.Sub(children...) }
func Summary(children ...H) H    { return gh.Summary(children...) }
func Sup(children ...H) H        { return gh.Sup(children...) }
func Table(children ...H) H      { return gh.Table(children...) }
func TBody(children ...H) H      { return gh.TBody(children...) }
func Td(children ...H) H         { return gh.Td(children...) }
func Template(children ...H) H   { return gh.Template(children...) }
func Textarea(children ...H) H   { return gh.Textarea(children...) }
func TFoot(children ...H) H      { return gh.TFoot(children...) }
func Th(children ...H) H         { return gh.Th(children...) }
func THead(children ...H) H      { return gh.THead(children...) }
func Time(children ...H) H       { return gh.Time(children...) }
func Title(v string) H           { return gh.Title(v) }
func Tr(children ...H) H         { return gh.Tr(children...) }
func U(children ...H) H          { return gh.U(children...) }
func Ul(children ...H) H         { return gh.Ul(children...) }
func Var(children ...H) H        { return gh.Var(children...) }
func StyleEl(children ...H) H    { return gh.StyleEl(children...) }
func Video(children ...H) H      { return gh.Video(children...) }
func Wbr(children ...H) H        { return gh.Wbr(children...) }
