package h

// The full HTML5 element vocabulary, one constructor per tag, minus the tags a
// via View has no business emitting: html, head, body, script, style, title,
// base, meta, link, template, slot and data are via's (the page shell, CSP'd
// scripts) or footguns (template/slot collide with composition, data with
// Datastar). Exotic or future tags go through El("tag", …).
//
// Mechanically uniform on purpose — every constructor is element{tag, kids} —
// so the whole file reads as a table, not code.

func A(kids ...H) H          { return element{tag: "a", kids: kids} }
func Abbr(kids ...H) H       { return element{tag: "abbr", kids: kids} }
func Address(kids ...H) H    { return element{tag: "address", kids: kids} }
func Area(kids ...H) H       { return element{tag: "area", kids: kids} }
func Article(kids ...H) H    { return element{tag: "article", kids: kids} }
func Aside(kids ...H) H      { return element{tag: "aside", kids: kids} }
func Audio(kids ...H) H      { return element{tag: "audio", kids: kids} }
func B(kids ...H) H          { return element{tag: "b", kids: kids} }
func Bdi(kids ...H) H        { return element{tag: "bdi", kids: kids} }
func Bdo(kids ...H) H        { return element{tag: "bdo", kids: kids} }
func Blockquote(kids ...H) H { return element{tag: "blockquote", kids: kids} }
func Br(kids ...H) H         { return element{tag: "br", kids: kids} }
func Button(kids ...H) H     { return element{tag: "button", kids: kids} }
func Canvas(kids ...H) H     { return element{tag: "canvas", kids: kids} }
func Caption(kids ...H) H    { return element{tag: "caption", kids: kids} }
func Cite(kids ...H) H       { return element{tag: "cite", kids: kids} }
func Code(kids ...H) H       { return element{tag: "code", kids: kids} }
func Col(kids ...H) H        { return element{tag: "col", kids: kids} }
func Colgroup(kids ...H) H   { return element{tag: "colgroup", kids: kids} }
func Datalist(kids ...H) H   { return element{tag: "datalist", kids: kids} }
func Dd(kids ...H) H         { return element{tag: "dd", kids: kids} }
func Del(kids ...H) H        { return element{tag: "del", kids: kids} }
func Details(kids ...H) H    { return element{tag: "details", kids: kids} }
func Dfn(kids ...H) H        { return element{tag: "dfn", kids: kids} }
func Dialog(kids ...H) H     { return element{tag: "dialog", kids: kids} }
func Div(kids ...H) H        { return element{tag: "div", kids: kids} }
func Dl(kids ...H) H         { return element{tag: "dl", kids: kids} }
func Dt(kids ...H) H         { return element{tag: "dt", kids: kids} }
func Em(kids ...H) H         { return element{tag: "em", kids: kids} }
func Embed(kids ...H) H      { return element{tag: "embed", kids: kids} }
func Fieldset(kids ...H) H   { return element{tag: "fieldset", kids: kids} }
func Figcaption(kids ...H) H { return element{tag: "figcaption", kids: kids} }
func Figure(kids ...H) H     { return element{tag: "figure", kids: kids} }
func Footer(kids ...H) H     { return element{tag: "footer", kids: kids} }
func Form(kids ...H) H       { return element{tag: "form", kids: kids} }
func H1(kids ...H) H         { return element{tag: "h1", kids: kids} }
func H2(kids ...H) H         { return element{tag: "h2", kids: kids} }
func H3(kids ...H) H         { return element{tag: "h3", kids: kids} }
func H4(kids ...H) H         { return element{tag: "h4", kids: kids} }
func H5(kids ...H) H         { return element{tag: "h5", kids: kids} }
func H6(kids ...H) H         { return element{tag: "h6", kids: kids} }
func Header(kids ...H) H     { return element{tag: "header", kids: kids} }
func Hgroup(kids ...H) H     { return element{tag: "hgroup", kids: kids} }
func Hr(kids ...H) H         { return element{tag: "hr", kids: kids} }
func I(kids ...H) H          { return element{tag: "i", kids: kids} }
func Iframe(kids ...H) H     { return element{tag: "iframe", kids: kids} }
func Img(kids ...H) H        { return element{tag: "img", kids: kids} }
func Input(kids ...H) H      { return element{tag: "input", kids: kids} }
func Ins(kids ...H) H        { return element{tag: "ins", kids: kids} }
func Kbd(kids ...H) H        { return element{tag: "kbd", kids: kids} }
func Label(kids ...H) H      { return element{tag: "label", kids: kids} }
func Legend(kids ...H) H     { return element{tag: "legend", kids: kids} }
func Li(kids ...H) H         { return element{tag: "li", kids: kids} }
func Main(kids ...H) H       { return element{tag: "main", kids: kids} }
func Map(kids ...H) H        { return element{tag: "map", kids: kids} }
func Mark(kids ...H) H       { return element{tag: "mark", kids: kids} }
func Menu(kids ...H) H       { return element{tag: "menu", kids: kids} }
func Meter(kids ...H) H      { return element{tag: "meter", kids: kids} }
func Nav(kids ...H) H        { return element{tag: "nav", kids: kids} }
func Noscript(kids ...H) H   { return element{tag: "noscript", kids: kids} }
func Object(kids ...H) H     { return element{tag: "object", kids: kids} }
func Ol(kids ...H) H         { return element{tag: "ol", kids: kids} }
func Optgroup(kids ...H) H   { return element{tag: "optgroup", kids: kids} }
func Option(kids ...H) H     { return element{tag: "option", kids: kids} }
func Output(kids ...H) H     { return element{tag: "output", kids: kids} }
func P(kids ...H) H          { return element{tag: "p", kids: kids} }
func Picture(kids ...H) H    { return element{tag: "picture", kids: kids} }
func Pre(kids ...H) H        { return element{tag: "pre", kids: kids} }
func Progress(kids ...H) H   { return element{tag: "progress", kids: kids} }
func Q(kids ...H) H          { return element{tag: "q", kids: kids} }
func Rp(kids ...H) H         { return element{tag: "rp", kids: kids} }
func Rt(kids ...H) H         { return element{tag: "rt", kids: kids} }
func Ruby(kids ...H) H       { return element{tag: "ruby", kids: kids} }
func S(kids ...H) H          { return element{tag: "s", kids: kids} }
func Samp(kids ...H) H       { return element{tag: "samp", kids: kids} }
func Search(kids ...H) H     { return element{tag: "search", kids: kids} }
func Section(kids ...H) H    { return element{tag: "section", kids: kids} }
func Select(kids ...H) H     { return element{tag: "select", kids: kids} }
func Small(kids ...H) H      { return element{tag: "small", kids: kids} }
func Source(kids ...H) H     { return element{tag: "source", kids: kids} }
func Span(kids ...H) H       { return element{tag: "span", kids: kids} }
func Strong(kids ...H) H     { return element{tag: "strong", kids: kids} }
func Sub(kids ...H) H        { return element{tag: "sub", kids: kids} }
func Summary(kids ...H) H    { return element{tag: "summary", kids: kids} }
func Sup(kids ...H) H        { return element{tag: "sup", kids: kids} }
func Table(kids ...H) H      { return element{tag: "table", kids: kids} }
func Tbody(kids ...H) H      { return element{tag: "tbody", kids: kids} }
func Td(kids ...H) H         { return element{tag: "td", kids: kids} }
func Textarea(kids ...H) H   { return element{tag: "textarea", kids: kids} }
func Tfoot(kids ...H) H      { return element{tag: "tfoot", kids: kids} }
func Th(kids ...H) H         { return element{tag: "th", kids: kids} }
func Thead(kids ...H) H      { return element{tag: "thead", kids: kids} }
func Time(kids ...H) H       { return element{tag: "time", kids: kids} }
func Tr(kids ...H) H         { return element{tag: "tr", kids: kids} }
func Track(kids ...H) H      { return element{tag: "track", kids: kids} }
func U(kids ...H) H          { return element{tag: "u", kids: kids} }
func Ul(kids ...H) H         { return element{tag: "ul", kids: kids} }
func Var(kids ...H) H        { return element{tag: "var", kids: kids} }
func Video(kids ...H) H      { return element{tag: "video", kids: kids} }
func Wbr(kids ...H) H        { return element{tag: "wbr", kids: kids} }
